/**
 * Registry of optional requirement IDs for level-up validation.
 * Backend logic evaluates by id; embeds display description.
 */
export const OPTIONAL_REQUIREMENTS = {
  NARRATION_1: 'REQ_NARRATION_1',
  NARRATIONS_2: 'REQ_NARRATIONS_2',
  NARRATIONS_3: 'REQ_NARRATIONS_3',
  NARRATIONS_6: 'REQ_NARRATIONS_6',
  HIGHLIGHT_1: 'REQ_HIGHLIGHT_1',
  HIGHLIGHTS_2: 'REQ_HIGHLIGHTS_2',
  HIGHLIGHTS_3: 'REQ_HIGHLIGHTS_3',
  HIGHLIGHTS_5: 'REQ_HIGHLIGHTS_5',
  COMBAT_1: 'REQ_COMBAT_1',
  COMBATS_C_PLUS_2: 'REQ_COMBATS_C_PLUS_2',
  COMBATS_B_PLUS_2: 'REQ_COMBATS_B_PLUS_2',
  COMBAT_A_PLUS_1: 'REQ_COMBAT_A_PLUS_1',
  COMBAT_WINS_B_PLUS_3: 'REQ_COMBAT_WINS_B_PLUS_3',
  MISSION_D_2: 'REQ_MISSION_D_2',
  MISSION_C_1: 'REQ_MISSION_C_1',
  MISSION_EQUIVALENT_4: 'REQ_MISSION_EQUIVALENT_4',
  MISSION_EQUIVALENT_B2B3_1: 'REQ_MISSION_EQUIVALENT_B2B3_1',
  MISSION_EQUIVALENT_A1_5: 'REQ_MISSION_EQUIVALENT_A1_5',
  MISSION_EQUIVALENT_A2A3_2: 'REQ_MISSION_EQUIVALENT_A2A3_2',
  MISSION_S_1: 'REQ_MISSION_S_1',
  ACHIEVEMENT_1: 'REQ_ACHIEVEMENT_1',
  ACHIEVEMENTS_2: 'REQ_ACHIEVEMENTS_2',
  ACHIEVEMENTS_8: 'REQ_ACHIEVEMENTS_8',
  PR_500: 'REQ_PR_500',
  CURE_2: 'REQ_CURE_2',
  CURE_5: 'REQ_CURE_5',
  CURE_10: 'REQ_CURE_10'
} as const;
